***Introduction:***

Welcome to this Google Colab notebook where we embark on a data analysis journey focused on Airbnb operations in two vibrant citiesâ€”Chicago and New Orleans. This Colab guides you through essential steps, from data download to cleaning and preparation, setting the stage for insightful visualizations using tools like Tableau.

***Project Overview:***

In this project, we delve into Airbnb listings data, exploring key attributes, handling null values, and preparing the data for visualization. The goal is to create a comprehensive BI dashboard using Tableau, offering a nuanced comparative examination of Airbnb's presence in Chicago and New Orleans.

***Scope of this Colab:***

**Data Download:** Fetching Airbnb data for both cities from Google Drive.

**Data Cleaning:** Addressing null values, ensuring data integrity for subsequent analysis.

**Data Exploration:** Identifying relevant columns and preparing them for Tableau.

**Exporting Cleaned Data:** Saving cleaned datasets for further analysis in Tableau Prep.

As we progress, each step is meticulously outlined, ensuring clarity and effectiveness in preparing your data for visualization. Let's dive in!

***Importing Required Packages:***

In [1]:
import pandas as pd
import requests
import io

***Assigning Google Drive file id's to city variables***

In [13]:
chicago_id = '15xEwy-m3TbcY10mugfFOIXDnug542Sm-'
new_orleans_id = '1SsDOVVKGjxgBKGuHYG4jNrLqBlColARv'

***Constructing URL for data download***

In [14]:
chicago_url = f'https://drive.google.com/uc?id={chicago_id}'
new_orleans_url = f'https://drive.google.com/uc?id={new_orleans_id}'

***Download the contents of the CSV file***

In [15]:
chicago_data = requests.get(chicago_url).content
new_orleans_data = requests.get(new_orleans_url).content

***Read the CSV file into a Pandas DataFrame***

In [16]:
chicago_df = pd.read_csv(io.StringIO(chicago_data.decode('utf-8')))
new_orleans_df = pd.read_csv(io.StringIO(new_orleans_data.decode('utf-8')))

***Adding city name as a column for easy convenience***

In [17]:
chicago_df['City'] = "Chicago"
new_orleans_df['City'] = "New Orleans"

***Checking the columns of both cities data***

In [18]:
print('Chicago Columns : ',list(chicago_df.columns))
print('New Orleans Columns : ',list(new_orleans_df.columns))

Chicago Columns :  ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'City']
New Orleans Columns :  ['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month', 'City']

***Gathered required columns and placed in a list namely req_columns for accessing further.***

In [19]:
req_columns = [
    'City','id', 'name', 'description',
    'host_id', 'host_name', 'host_since','host_location', 'host_is_superhost', 'host_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
    'neighbourhood_cleansed', 'latitude', 'longitude',
    'property_type', 'room_type', 'accommodates', 'bedrooms', 'beds',
    'price', 'minimum_nights', 'availability_30', 'availability_60', 'availability_90', 'availability_365',
    'number_of_reviews', 'review_scores_rating', 'reviews_per_month',
    'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms'
]

***Assigning required columns from main data frame to new data frame to work on.***

In [20]:
chicago_final_columns = chicago_df[req_columns]
new_orleans_final_columns = new_orleans_df[req_columns]

***Replacing null values***

In [21]:
# replacing null values with zero for bedrooms column
chicago_final_columns['bedrooms'].fillna(0, inplace = True)

# replacing null values with 'NA' for description columns in view of less rows of data with null.
chicago_final_columns['description'].fillna('NA', inplace = True)

# replacing null values with zero for beds column
chicago_final_columns['beds'].fillna(0, inplace = True)

# replacing null values with f (false) for host_is_superhost column, assuming by default no one is superhost
chicago_final_columns['host_is_superhost'].fillna('f', inplace = True)

# replacing null values in 'reviews_per_month' with a placeholder value (assuming placeholder is 0)
chicago_final_columns['reviews_per_month'].fillna(0, inplace=True)

<ipython-input-21-3df45857eb43>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chicago_final_columns['bedrooms'].fillna(0, inplace = True)
<ipython-input-21-3df45857eb43>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chicago_final_columns['description'].fillna('NA', inplace = True)
<ipython-input-21-3df45857eb43>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chicago_final_columns['beds'].fillna(0, inplace = True)
<ipython-input-21-3df45857eb43>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chicago_final_columns['host_is_superhost'].fillna('f', inplace = True)
<ipython-input-21-3df45857eb43>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chicago_final_columns['reviews_per_month'].fillna(0, inplace=True)

In [22]:
# replacing null values in 'review_scores_rating' with a mean value (assuming placeholder is the mean)
chicago_mean_rating = chicago_final_columns['review_scores_rating'].mean()
chicago_final_columns['review_scores_rating'].fillna(chicago_mean_rating, inplace=True)

<ipython-input-22-b05b64796b67>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chicago_final_columns['review_scores_rating'].fillna(chicago_mean_rating, inplace=True)

In [23]:
# replacing null values with zero for bedrooms column
new_orleans_final_columns['bedrooms'].fillna(0, inplace = True)

# replacing null values with 'NA' for description columns in view of less rows of data with null.
new_orleans_final_columns['description'].fillna('NA', inplace = True)

# replacing null values with zero for beds column
new_orleans_final_columns['beds'].fillna(0, inplace = True)

# replacing null values with f (false) for host_is_superhost column, assuming by default no one is superhost
new_orleans_final_columns['host_is_superhost'].fillna('f', inplace = True)

# replacing null values in 'reviews_per_month' with a placeholder value (assuming placeholder is 0)
new_orleans_final_columns['reviews_per_month'].fillna(0, inplace=True)

<ipython-input-23-bca590e878e0>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_orleans_final_columns['bedrooms'].fillna(0, inplace = True)
<ipython-input-23-bca590e878e0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_orleans_final_columns['description'].fillna('NA', inplace = True)
<ipython-input-23-bca590e878e0>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_orleans_final_columns['beds'].fillna(0, inplace = True)
<ipython-input-23-bca590e878e0>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_orleans_final_columns['host_is_superhost'].fillna('f', inplace = True)
<ipython-input-23-bca590e878e0>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_orleans_final_columns['reviews_per_month'].fillna(0, inplace=True)

In [24]:
# replacing null values in 'review_scores_rating' with a mean value (assuming placeholder is the mean)
new_orleans_mean_rating = new_orleans_final_columns['review_scores_rating'].mean()
new_orleans_final_columns['review_scores_rating'].fillna(new_orleans_mean_rating, inplace=True)

<ipython-input-24-38478a0f744e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_orleans_final_columns['review_scores_rating'].fillna(new_orleans_mean_rating, inplace=True)

***Checking for null value columns for cleaning***

In [25]:
# Create a DataFrame for Chicago with information about columns for a quick understanding
chicago_info = pd.DataFrame({
    'Column': chicago_final_columns.columns,
    'Data Type': chicago_final_columns.dtypes.values,
    'Non-Null Count': chicago_final_columns.count().values,
    'Null Count': chicago_final_columns.isnull().sum().values
})

#Setting the max rows to 100 for display purpose
pd.set_option('display.max_rows',100)

# Sorting by Null Count to identify the null values easily
chicago_info.sort_values(by='Null Count',ascending=False)

# Filter to show only columns with null values
chicago_info[chicago_info['Null Count'] > 0]

          Column Data Type  Non-Null Count  Null Count
7  host_location    object            6974        1554

In [26]:
# Create a DataFrame for New Orleans with information about columns for a quick understanding
new_orleans_info = pd.DataFrame({
    'Column': new_orleans_final_columns.columns,
    'Data Type': new_orleans_final_columns.dtypes.values,
    'Non-Null Count': new_orleans_final_columns.count().values,
    'Null Count': new_orleans_final_columns.isnull().sum().values
})

#Setting the max rows to 100 for display purpose
pd.set_option('display.max_rows',100)

# Sorting by Null Count to identify the null values easily
new_orleans_info.sort_values(by='Null Count', ascending=False)

# Filter to show only columns with null values
new_orleans_info[chicago_info['Null Count'] > 0]

          Column Data Type  Non-Null Count  Null Count
7  host_location    object            5035        1748

***Importing cleaned data to CSV***

In [27]:
chicago_final_columns.to_csv('chicago_cleaned.csv', sep=',', index=True, encoding='utf-8')
new_orleans_final_columns.to_csv('new_orleans_cleaned.csv', sep=',', index=True, encoding='utf-8')

**Now, we will continue with the downloaded data to perform some formatting in Tableau Prep for further analysis in Tableau and for creating dashboard.**

**Thank you..!**
###**~ Prasad Gondala**